learning_log/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^users/', include('users.urls')),
    url(r'', include('learning_logs.urls')),
]

learning_logs/urls.py
"""Defines url patterns for learning_logs."""
from django.conf.urls import url
from . import views

app_name = 'learning_logs'

urlpatterns = [
    # Base page
    url(r'^base$', views.base, name='base'),

    # Base_bak page
    url(r'^base_bak$', views.base_bak, name='base_bak'),

    # Home page
    url(r'^$', views.index, name='index'),

    # About page
    url(r'^about/$', views.about, name='about'),

    # Topics page: shows all topics
    url(r'^topics/$', views.topics, name='topics'),

    # Detail page for a single topic
    url(r'^topics/(?P<topic_id>\d+)/$', views.topic, name='topic'),

    # New topic form page
    url(r'^new_topic/$', views.new_topic, name='new_topic'),

    # New entry page: allows user to add a new entry
    url(r'^new_entry/(?P<topic_id>\d+)/$', views.new_entry, name='new_entry'),

    # Page for editing an entry
    url(r'^edit_entry/(?P<entry_id>\d+)/$', views.edit_entry, name='edit_entry'),

    # Markdown cheatsheet page
    url(r'^md_cheatsheet/$', views.md_cheatsheet, name='md_cheatsheet'),

]

users/urls.py
"""Defines url patterns for users."""
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views

app_name = 'users'

urlpatterns = [
    # Login page
    # url(r'^login/$', login, {'template_name': 'users/login.html'}, 
        # name='login'),
    url(r'^login$', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    
    # Logout page
    url(r'^logout/$', views.logout_view, name='logout'),

    # Registration page
    url(r'^register/$', views.register, name='register'),
]

learning_logs/models.py
from pagedown.widgets import PagedownWidget
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

# Create your models here.
class Topic(models.Model):
    """A topic the user is learning about"""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        """Return a string representation of the model."""
        return self.text

class Entry(models.Model):
    """Something specific learned about a topic."""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    entry = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        """Return a string representation of the model."""
        if len(self.entry) > 50:
            return self.entry[:50] + '...'
        else:
            return self.entry

    # def set_localtime(self):
    #     self.localtime = timezone.localtime(self.date_added)

learning_logs/forms.py
from pagedown.widgets import PagedownWidget
# from markdown_deux.templatetags.markdown_deux_tags import markdown_allowed
from django import forms
from .models import Topic, Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}

class EntryForm(forms.ModelForm):
    entry = forms.CharField(widget=PagedownWidget())

    class Meta:
        model = Entry
        fields = ['entry']
        labels = {'entry': ''}
        

learning_logs/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.db.models.functions import Lower
from django.utils import timezone

from .models import Topic, Entry
from .forms import TopicForm, EntryForm

def check_topic_owner(owner, user):
    """Checks if the current user is the topic owner."""
    if owner != user:
        raise Http404
    else:
        return

# Create your views here.
def base(request):
    return render(request, 'learning_logs/base.html')

def base_bak(request):
    return render(request, 'learning_logs/base_bak.html')

def index(request):
    """The home page for learning_logs."""
    return render(request, 'learning_logs/index.html')

def about(request):
    """The about page for learning_logs."""
    return render(request, 'learning_logs/about.html')

def md_cheatsheet(request):
    return render(request, 'learning_logs/md_cheatsheet.html')

@login_required
def topics(request):
    """Shows all topics."""
    topics = Topic.objects.filter(owner=request.user).order_by(Lower('text').asc())
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)

@login_required
def topic(request, topic_id):
    """Show a single topic and all its entries."""
    topic = get_object_or_404(Topic, id=topic_id)

    # Make sure the topic belongs to the current user
    check_topic_owner(topic.owner, request.user)

    entries = topic.entry_set.order_by('-id')
    context = {'topic':topic, 'entries':entries}
    return render(request, 'learning_logs/topic.html', context)

@login_required
def new_topic(request):
    """Add a new topic."""
    if request.method != 'POST':
        # No data submitted. Create a blank form.
        form = TopicForm()
    else:
        # POST data submitted. Process data.
        form = TopicForm(request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return HttpResponseRedirect(reverse('learning_logs:topics'))

    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)

@login_required
def new_entry(request, topic_id):
    """Add a new entry for a selected topic."""
    topic = Topic.objects.get(id=topic_id)

    # Make sure entry topic belongs to the current user
    check_topic_owner(topic.owner, request.user)

    if request.method != 'POST':
        # No data submitted. Create a blank form.
        form = EntryForm()

    else:
        # POST data submitted. Process data.
        form = EntryForm(request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.owner = request.user
            new_entry.save()
            return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic_id]))

    context = {'form':form, 'topic':topic}
    return render(request, 'learning_logs/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
    """Edit an existing entry."""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic

    # Make sure entry belongs to the current user
    check_topic_owner(topic.owner, request.user)

    if request.method != 'POST':
        # Initial request: pre-fill form with the current entry.
        form = EntryForm(instance=entry)

    else:
        # POST data submitted. Process data.
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic.id]))

    context = {'form':form, 'topic':topic, 'entry':entry}
    return render(request, 'learning_logs/edit_entry.html', context)

learning_logs/templates/learning_logs/about.html
{% extends 'learning_logs/base.html' %}
{% load static %}

{% block header %}
    <h1>About Learning Logs</h1>
{% endblock header %}

{% block content %}

  <!-- "ABOUT" PANEL -->
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Origins</h3>
    </div>
    <div class="panel-body">
      <p>Learning Logs takes its name (and most of its structure and   functionality) from the web application tutorial found in Chapters 18 - 20   in the beginner's python programming book <a href="http://ehmatthes.github.io/pcc/"><strong>Python Crash Course</strong></a> by Eric Matthes.</p>
    
      <p>Some modifications have been made to the original design:</p>
      <ul>
        <p>
          <li>used a <a href="https://getbootstrap.com/components/#navbar-fixed-top"><b>fixed-top navbar</b></a> instead of a static-top navbar</li>
        </p>
    
        <p>
          <li>added some more <a href="http://getbootstrap.com/css/#buttons"><strong>bootstrap3 buttons</strong></a></li>
        </p>

        <p>
          <li>added this "about" page with <a href="http://getbootstrap.com/components/#panels"><strong>panels</strong></a></li>
        </p>
    
        <p>
          <li>sorted user's topics alphabetically instead of by date added:   required learning more about <a href="https://docs.djangoproject.com/en/1.10/ref/models/querysets/"><strong>Django's QuerySet API</strong></a>   and the <a href="https://docs.djangoproject.com/en/1.10/ref/models/querysets/#order-by"><b>ordered_by method</b></a></li>
        </p>
        <p>
          <li>added the image of a happy log on the index page: original image   found on March 11, 2016 on www.kingofwallpapers.com via a   google search for images of logs; modified by me using Adobe Photoshop CS5.</li>
        </p>
    
        <p>
          <li>added timezone aware dates for entry views rendered client-side on the "topic" page: required some javascript code (suggested by the hubs) and installation of <a href="https://momentjs.com/"><strong>moment.js</strong></a> (an   amazing little package that I found which provides formatting options   for javascript date objects! ... required downloading and using   moment.min.js as a <a href="https://docs.djangoproject.com/en/1.10/howto/static-files/"><strong>static file</strong></a>)</li>
        </p>
    
        <p>
          <li>used a <a href="https://daringfireball.net/projects/markdown/syntax">  <strong>markdown</strong></a> editor/viewer for the "new entry", "edit   entry", and "topic" pages: required installation of the projects <a href=  "https://github.com/timmyomahony/django-pagedown"><strong>django-pagedown  </strong></a> (for the markdown editing) and <a href="https://github.com/trentm/django-markdown-deux"><strong>django-markdown-deux</strong></a> (for viewing markdown entries ... and for safely escaping raw HTML)</li>
        </p>
      </ul>
    </div>
  </div><!-- END "ABOUT" PANEL-->

  <!-- "HOW TO USE" PANEL-->
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">How to Use Learning Logs</h3>
    </div>
    <div class="panel-body">
      <ol>
        <p>
          <h3><li>Registration is closed.</li></h3>
        </p>

        <p>
          As of 2019.03.06 this app is no longer accepting new account registration.
        </p>

        <!-- <p>
          <h3><li><a href="{% url 'users:register' %}">Register</a> for your free account.</li></h3>
        </p>

        <p>
          Click on the "register" link found on the right side of the navigation bar at the top of the page.
        </p>

        <p>
          <img src="{% static '/images/register.jpg' %}" class="img-responsive img-rounded img-thumbnail" alt="Responsive image"/>        
        </p>

        <br>

        <p>
          Create a unique username and password, then click on the "register" button at the bottom of the form.
        </p>

        <p>
          <img src="{% static '/images/register_click.jpg' %}" class="img-responsive img-rounded img-thumbnail" alt="Responsive image"/>        
        </p>

        <br>

        <p>
          <h3><li>Go do some learning about <a href="http://www.macwright.org/2017/01/28/numbers.html"><b>stuff</b></a> ... maybe <a href="https://www.engadget.com/2017/02/17/when-vending-machines-attack/">things</a>.</li></h3>
        </p> -->

        <br>

        <p>
          <h3><li>Come back to Learning Logs and <a href="{% url 'users:login' %}"><b>Log in</b></a> to your account.</h3> Click on the "log in " link found on the right side of the navigation bar at the top of the page.</li>
        </p>

        <p>
          <img src="{% static '/images/login.jpg' %}" class="img-responsive img-rounded img-thumbnail" alt="Responsive image"/>        
        </p>

        <br>

        <p>
          <h3><li>Add a topic.</li></h3>
        </p>

        <p>
          Click on the "Topics" tab found toward the middle of the navigation bar at the top of the page.
        </p>

        <p>
          <img src="{% static '/images/topics_click.jpg' %}" class="img-responsive img-rounded img-thumbnail" alt="Responsive image"/>
        </p>

        <br>

        <p>
          Click on the "add a topic" button at the bottom of the topics list panel.
        </p>

        <p>
          <img src="{% static '/images/topics_add.jpg' %}" class="img-responsive img-rounded img-thumbnail" alt="Responsive image"/>
        </p>

        <br>

        <p>
          Type the new topic's name in the form. Then click the "add topic" button at the bottom of the form to save that topic.
        </p>

        <p>
          <img src="{% static '/images/topic_name.jpg' %}" class="img-responsive img-rounded img-thumbnail" alt="Responsive image"/>
        </p>

        <br>

        <p>
          <h3><li>Add an entry for that topic.</h3> Click on the topic's name.</li>
        </p>

        <p>
          <img src="{% static '/images/topic_name_click.jpg' %}" class="img-responsive img-rounded img-thumbnail" alt="Responsive image"/>
        </p>

        <br>

        <p>
          Click the "add an entry" button to go to the text editor.
        </p>

        <p>
          <img src="{% static '/images/add_entry.jpg' %}" class="img-responsive img-rounded img-thumbnail" alt="Responsive image"/>
        </p>

        <br>

        <p>
          In the text editor pane, type up your entry. Scroll down to see a preview of that entry in the preview pane. Click the "save entry" button when done.
        </p>

        <p>
          <img src="{% static '/images/entry_write.jpg' %}" class="img-responsive img-rounded img-thumbnail" alt="Responsive image"/>
        </p>

        <br>

        <p>
          <h3><li>Edit an entry if necessary.</h3> Click on the "edit entry" link found in the entry's time and date header.</li>
        </p>

        <p>
          <img src="{% static '/images/edit_entry.jpg' %}" class="img-responsive img-rounded img-thumbnail" alt="Responsive image"/>
        </p>

        <br>

        <p>
          Dress that entry up with some <a href="{% url 'learning_logs:md_cheatsheet' %}"><b>Markdown</b></a> if you're feeling fancy. Click the "save changes" button when done.
        </p>

        <p>
          <img src="{% static '/images/entry_edit_markdown.jpg' %}" class="img-responsive img-rounded img-thumbnail" alt="Responsive image"/>
        </p>

        <br>

        <p>
          <h3><li>Rinse and repeat.</li></h3>
        </p>
      </ol>
    </div>
  </div><!-- END "HOW TO USE" PANEL-->

  <!-- MARKDOWN INFO PANEL -->
  <div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">About Markdown</h3>
  </div>
  <div class="panel-body">
    <p>
      Markdown is like shorthand for HTML. It can do a lot of what HTML does to text, but with fewer keystrokes. I chose to include it as a feature of Learning Logs because it provides the ability to add meaning and readability to what would otherwise be plain text entries. 
    </p>
    <p>
      Click <b><a href="http://daringfireball.net/projects/markdown/syntax" target="_blank">here</a></b> to learn lots more about Markdown. 
    </p>
    <p>
      Click on the "Markdown Cheatsheet" link in the middle of the navigation bar at the top of the page for help with some common syntax uses. The page opens in a new tab.
    </p>
    <p>
      ENJOY! :D
    </p>
  </div>

{% endblock content %}

learning_logs/templates/learning_logs/base.html
{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <!-- <meta name="description" content="">
    <meta name="author" content=""> -->
    
    <style>
      body{   
        padding-top:50px; 
      }
      /* uncomment the following if view acts buggy on small devices */
      /*@media(max-width: 768px){
        body{ margin-top: 0px;    
          } 
        }*/
    </style>

    <title>Learning Logs</title>

  </head>

  <body>

    <!-- Static navbar -->
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'learning_logs:index' %}">LEARNING LOGS</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'learning_logs:about' %}">About</a></li>
            {% if user.is_authenticated %}
              <li><a href="{% url 'learning_logs:topics' %}">Topics</a></li>
            {% else %}
              <li><a href="{% url 'users:login' %}">Topics</a></li>
            {% endif %}
            <li><a href="{% url 'learning_logs:md_cheatsheet' %}">Markdown Cheatsheet</a></li>
          </ul>
          {% if user.is_authenticated %}
            <ul class="nav navbar-nav navbar-right">
              <li class="active"><a>Hello, {{ user.username }}!</a></li>
              <li><a href="{% url 'users:logout' %}">log out</a></li>
            </ul>
          {% else %}
            <ul class="nav navbar-nav navbar-right">
              <!-- <li><a href="{% url 'users:register' %}">register</a></li> -->
              <li><a href="{% url 'users:login' %}">log in</a></li>
            </ul>
          {% endif %}
        </div><!--/.nav-collapse -->
      </div>
    </nav>


    <div class="container">
      
      <div class="page-header">
        {% block header %}{% endblock header %}
      </div>

      <div>
        {% block content %}{% endblock content %}
      </div>

    </div> <!-- /container -->

  </body>
</html>

learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <h1><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></h1>
{% endblock header %}

{% block content %}

  <div class="panel panel-default">

    <!-- PANEL HEADING -->
    <div class="panel-heading">
      <h3 class="panel-title">Edit Entry</h3>
    </div>

    <!-- PANEL BODY -->
    <div class="panel-body">
   
      <p><b><a href="http://daringfireball.net/projects/markdown/syntax" target="_blank">Markdown syntax</a></b> allowed. Raw HTML tags function (sort of) in the preview, but are ignored on save and appear as plain text on {{ topic }}'s entries page.</p>
      
      {{ form.media }}
      
      <form action="{% url 'learning_logs:edit_entry' entry.id %}" method='post' class="form-group">
        {% csrf_token %}
        
        {% buttons %}
          <button name="submit" class="btn btn-primary">save changes</button>
          <a href="{% url 'learning_logs:topic' topic.id %}" class="btn btn-danger">cancel</a>
        {% endbuttons %}

        <style>
          .wmd-panel {
            margin-left: 0;
            margin-right: 0;
            margin-bottom: 10px;
            width: 0;
            min-width: 100%;
          }
        </style>
        
        {{ form }}
      
        {% buttons %}
          <button name="submit" class="btn btn-primary">save changes</button>
          <a href="{% url 'learning_logs:topic' topic.id %}" class="btn btn-danger">cancel</a>
        {% endbuttons %}
    
      </form>
    </div>

  </div>

{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends 'learning_logs/base.html' %}
{% load static %}

{% block header %}
    <div class="jumbotron">
      <h1>A learning log is a happy log.</h1>
    </div>
{% endblock header %}

{% block content %}
  <div>
    <img src="{% static '/images/happy_log.jpg' %}" class="img-responsive img-rounded" alt="Responsive image"/>
  </div>

{% endblock content %}

learning_logs/templates/learning_logs/md_cheatsheet.html
{% extends 'learning_logs/base.html' %}
{% load markdown_deux_tags%}

{% block header %}
    <h1>Log your learnings using Markdown!</h1>
{% endblock header %}

{% block content %}
  
  {% markdown_cheatsheet %}

{% endblock content %}

learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <h1><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></h1>
{% endblock header %}

{% block content %}
  <div class="panel panel-default">
    <!-- PANEL HEADING -->
    <div class="panel-heading">
      <h3 class="panel-title">Add an Entry</h3>
    </div>

    <!-- PANEL BODY -->
    <div class="panel-body">
      <p><b><a href="http://daringfireball.net/projects/markdown/syntax" target="_blank">Markdown syntax</a></b> allowed. Raw HTML tags function (sort of) in the preview, but are ignored on save and appear as plain text on {{ topic }}'s entries page.</p>

      {{ form.media }}

      <form action="{% url 'learning_logs:new_entry' topic.id %}" method='post' class="form-group">

        {% csrf_token %}

        {% buttons %}
          <button name="submit" class="btn btn-primary">save entry</button>
          <a href="{% url 'learning_logs:topic' topic.id %}" class="btn btn-danger">cancel</a>
        {% endbuttons %}

        <style>
          .wmd-panel {
            margin-left: 0;
            margin-right: 0;
            margin-bottom: 10px;
            width: 0;
            min-width: 100%;
          }
        </style>
      
        {{ form }}
      
        {% buttons %}
          <button name="submit" class="btn btn-primary">save entry</button>
          <a href="{% url 'learning_logs:topic' topic.id %}" class="btn btn-danger">cancel</a>
        {% endbuttons %}

      </form>
    </div>
    
  </div>

{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <h1>Add a New Topic</h1>
{% endblock header %}

{% block content %}

  <form action="{% url 'learning_logs:new_topic' %}" method='post' class="  form-group">

    <div class="panel panel-default">
    
      <!-- PANEL HEADING -->
      <div class="panel-heading">
        <h3 class="panel-title">More learning?! Yay!!</h3>
      </div>

      <!-- PANEL BODY -->
      <div class="panel-body">
        {% csrf_token %}
        {% bootstrap_form form %}
      </div>

    </div>

    {% buttons %}
      <button name="submit" class="btn btn-primary">add topic</button>
      <a href="{% url 'learning_logs:topics' %}" class="btn btn-danger">cancel</a>
    {% endbuttons %}

  </form>

{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}
{% load static %}
{% load markdown_deux_tags %}
{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% block header %}
  <h1>{{ topic }}</h1>
{% endblock header %}

{% block content %}
  <!-- "ADD AN ENTRY" AND "BACK TO TOPICS" BUTTONS -->
  <p>
    <a href="{% url 'learning_logs:new_entry' topic.id %}" class="btn btn-primary">add an entry</a>  <a href="{% url 'learning_logs:topics' %}" class="btn btn-info">back to topics</a>
  </p>

  {% for entry in entries %}
    <div class="panel panel-default"><!-- begin entry panel -->
      <!-- PANEL HEADING -->
      <div class="panel-heading">
        <h3>
          <span id="{{ entry.id }}">{{ entry.date_added|date:'c' }}</span>
          <script src="{% static '/js/moment.min.js' %}"></script>
          <script>
            var entry_time = document.getElementById("{{ entry.id }}")
            var js_date = new Date(Date.parse(entry_time.innerHTML))
            // var day = local_time.getDay()
            // var js_date = toJSDate(entry_time.innerHTML)
            var formatted_dt = moment(js_date).format("ddd - D MMM YYYY - h:mm a")
            document.getElementById("{{ entry.id }}").innerHTML = formatted_dt
          </script>
          <small>
            <a href="{% url 'learning_logs:edit_entry' entry.id %}">edit entry</a>
          </small>
        </h3>
      </div>
      
      <!-- PANEL BODY -->
      <div class="panel-body">
        {{ entry.entry|markdown }}
      </div>

    </div><!-- /entry panel -->

    <!-- "ADD AN ENTRY" AND "BACK TO TOPICS" BUTTONS -->
    <p>
      <a href="{% url 'learning_logs:new_entry' topic.id %}" class="btn btn-primary">add an entry</a>  <a href="{% url 'learning_logs:topics' %}" class="btn btn-info">back to topics</a>
    </p>

  <!-- IF THERE ARE NO ENTRIES FOR THE TOPIC -->
  {% empty %}
    <div class="well well-sm">
      <h4>There are no entries for this topic yet.</h4>
    </div>

  {% endfor %}  
{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap3 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% block header %}
  <h1>Topics</h1>
{% endblock header %}

{% block content %}

  <div class="panel panel-default">

    <!-- PANEL HEADING -->
    <div class="panel-heading">
      <h3 class="panel-title">"The cure for boredom is curiosity. There is no cure for curiosity." <i><a href="http://quoteinvestigator.com/2015/11/01/cure/"> -- Ellen Parr (Reader's Digest, 1980)</a></i></h3>
    </div>

    <!-- PANEL BODY -->
    <div class="panel-body">
      <!-- show topics -->
      {% for topic in topics %}
        <h4><p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p></h4>
      {% empty %}
        <p>No topics have been added yet.</p>
      {% endfor %}
    </div>

  </div>

  <!-- "add a topic" button -->
  <p>
    <a href="{% url 'learning_logs:new_topic' %}" class="btn btn-primary">add a topic</a>
  </p>

{% endblock content %}