learning_log/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^users/', include('users.urls')),
    url(r'', include('learning_logs.urls')),
]

learning_logs/urls.py
"""Defines url patterns for learning_logs."""
from django.conf.urls import url
from . import views

app_name = 'learning_logs'

urlpatterns = [
    # Base page
    url(r'^base$', views.base, name='base'),

    # Base_bak page
    url(r'^base_bak$', views.base_bak, name='base_bak'),

    # Home page
    url(r'^$', views.index, name='index'),

    # About page
    url(r'^about/$', views.about, name='about'),

    # Topics page: shows all topics
    url(r'^topics/$', views.topics, name='topics'),

    # Detail page for a single topic
    url(r'^topics/(?P<topic_id>\d+)/$', views.topic, name='topic'),

    # New topic form page
    url(r'^new_topic/$', views.new_topic, name='new_topic'),

    # New entry page: allows user to add a new entry
    url(r'^new_entry/(?P<topic_id>\d+)/$', views.new_entry, name='new_entry'),

    # Page for editing an entry
    url(r'^edit_entry/(?P<entry_id>\d+)/$', views.edit_entry, name='edit_entry'),

    # Markdown cheatsheet page
    url(r'^md_cheatsheet/$', views.md_cheatsheet, name='md_cheatsheet'),

]

users/urls.py
"""Defines url patterns for users."""
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views

app_name = 'users'

urlpatterns = [
    # Login page
    # url(r'^login/$', login, {'template_name': 'users/login.html'}, 
        # name='login'),
    url(r'^login$', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    
    # Logout page
    url(r'^logout/$', views.logout_view, name='logout'),

    # Registration page
    url(r'^register/$', views.register, name='register'),
]

users/models.py
from django.db import models
# from django.contrib.auth.models import AbstractUser

# Create your models here.
# class User(AbstractUser):
    # timezone = models.CharField(max_length=30, blank=True)

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
import pytz

# TIMEZONE_CHOICES = [(x, x) for x in pytz.common_timezones]

# class UserCreationForm(UserCreationForm):
#     timezone = forms.ChoiceField(choices=TIMEZONE_CHOICES, label="Timezone", required=True)
#     # timezone = forms.ChoiceField(choices=[(x, x) for x in pytz.common_timezones], required=True)

#     class Meta:
#         model = User
#         fields = ("username", "timezone", "password1", "password2")

#     def save(self, commit=True):
#         user = super(UserCreationForm, self).save(commit=False)
#         user.timezone = timezone
#         if commit:
#             user.save()
#         return user

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import UserCreationForm

# Create your views here.
def logout_view(request):
    """Log the user out."""
    logout(request)
    return HttpResponseRedirect(reverse('learning_logs:index'))

def register(request):
    """Register a new user."""
    if request.method != 'POST':
        # Display blank registration form
        form = UserCreationForm()

    else:
        # Process completed form
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            # Log the user in and redirect to home page
            authenticated_user = authenticate(username=new_user.username, password=request.POST['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('learning_logs:index'))

    context = {'form':form}
    return render(request, 'users/register.html', context)

users/templates/users/login.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap3 %}

{% block header %}
  <h1>Log In to Your Account</h1>
{% endblock header %}

{% block content %}

  <form method="post" action="{% url 'users:login' %}" class="form">

    <div class="panel panel-default">

      <div class="panel-heading">

        {% if form.errors %}

          <h3 class="panel-title">Your username and password did not match. Please try again.</h3>

        {% else %}

          <h3 class="panel-title">Back for more?! You Awesome Winning Learner, you!</h3>

        {% endif %}

      </div>

      <div class="panel-body">

          {% csrf_token %}
          {% bootstrap_form form %}
      </div>

    </div>

    <input type="hidden" name="next" value="{% url 'learning_logs:topics' %}" />
    {% buttons %}
      <button name="submit" class="btn btn-primary">log in</button>
      <!-- <span style="padding-left:10px;">Need an account? <a href="{% url 'users:register' %}">register here</a></span> -->
    {% endbuttons %}

  </form>

{% endblock content %}

users/templates/users/register.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap3 %}

{% block header %}
  <h1>Register an Account</h1>
{% endblock header %}

{% block content %}
  <form method="post" action="{% url 'users:register' %}" class="form">

    <div class="panel panel-default">

      <div class="panel-heading">
        <h3 class="panel-title">Go learn something! Then come back here and write about it! So great!</h3>
      </div>

      <div class="panel-body">


          {% csrf_token %}
        
          {% bootstrap_form form %}

      </div>
    </div>
    
    <!-- <input type="hidden" name="next" value="{% url 'learning_logs:topics' %}" />
    {% buttons %}
      <button name="submit" class="btn btn-primary">register</button>
      <span style="padding-left:10px;">Already have an account? <a href="{% url 'users:login' %}">login here</a></span>
    {% endbuttons %} -->
    <div>Registration is closed.</div>

  </form>

{% endblock content %}ß